version: "3.0"

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

volumes:
  postgres: